"""empty message

Revision ID: 085a9e297ef7
Revises: c8cc914e9bc6
Create Date: 2023-06-24 23:16:51.353372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085a9e297ef7'
down_revision = 'c8cc914e9bc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('phone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'phone')
    # ### end Alembic commands ###
