"""init statics

Revision ID: 34906c8f924c
Revises: f6ff03e0bf3a
Create Date: 2023-07-03 14:45:43.859504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34906c8f924c'
down_revision = 'f6ff03e0bf3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statics')
    # ### end Alembic commands ###
