"""init db

Revision ID: 83f9f7b08953
Revises: 
Create Date: 2023-06-17 01:57:05.713592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f9f7b08953'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), server_default='', nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_groups', sa.String(), nullable=False),
    sa.Column('dtime', sa.TIMESTAMP(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('reg_time_start', sa.TIME(), nullable=False),
    sa.Column('reg_time_finish', sa.TIME(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter', sa.String(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    op.drop_table('services')
    op.drop_table('registrations')
    op.drop_table('mailings')
    op.drop_table('clients')
    # ### end Alembic commands ###
