"""init db

Revision ID: ba0cf5d3d798
Revises: 83f9f7b08953
Create Date: 2023-06-17 04:56:56.172658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0cf5d3d798'
down_revision = '83f9f7b08953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('status', sa.String(), server_default='enabled', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'status')
    # ### end Alembic commands ###
