"""service ordering

Revision ID: c8cc914e9bc6
Revises: ba0cf5d3d798
Create Date: 2023-06-20 06:47:05.683654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cc914e9bc6'
down_revision = 'ba0cf5d3d798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('ordering', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'ordering')
    # ### end Alembic commands ###
