"""empty message

Revision ID: f6ff03e0bf3a
Revises: 085a9e297ef7
Create Date: 2023-06-25 23:33:36.729257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ff03e0bf3a'
down_revision = '085a9e297ef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'user_id')
    # ### end Alembic commands ###
